name: Loop Over Branches and Trigger Workflows

on:
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    strategy:
      matrix:
        target:
            - log_level: none
            - log_level: error
            - log_level: warning
            - log_level: info
            - log_level: debug
            - log_level: verrbose
            - log_level: default

    steps:
      - name: Trigger workflow
        run: |
          ref="${GITHUB_REF_NAME}"
          echo "Current branch: $ref"
          gh workflow run test.yaml \
            --ref $ref \
            --repo $GITHUB_REPOSITORY \
            -f target=all \
            -f log_level=${{ matrix.target.log_level }} \
            -f latest-builder=true

  modify-and-trigger:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    strategy:
      matrix:
        target:
          - branch: rtti/3.3.x
            input_target: all
            log_level: default
            latest_builder: true
            replace_old: 'CONFIG_IRGEND_WAS=y,# CONFIG_TARGET_IDF is not set'
            replace_new: '# CONFIG_IRGEND_WAS is not set,CONFIG_TARGET_IDF=y'
          - branch: exceptions/3.3.x
            input_target: all
            log_level: default
            latest_builder: true
            replace_old: ''
            replace_new: ''
          - branch: performance/3.3.x
            input_target: all
            log_level: default
            latest_builder: true
            replace_old: ''
            replace_new: ''
    
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ env.GH_TOKEN }}

      - name: Get current branch name
        id: branch
        run: echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

      - name: Create/switch to new branch and make changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -B ${{ matrix.target.branch }}
          echo "// Auto-generated on $(date)" > generated_file.txt
          git add generated_file.txt
          git commit -m "Automated commit to ${{ matrix.target.branch }}" || echo "Nothing to commit"
          git push origin ${{ matrix.target.branch }} --force
      - name: Split and process target list
        run: |
          IFS=',' read -ra old <<< "${{ github.event.inputs.replace_old }}"
          for o in "${old[@]}"; do
            echo "Processing $o"
            # Insert whatever logic you need per target
          done

          
      - name: Trigger workflow on new branch
        run: |
          gh workflow run test.yaml \
            --ref ${{ matrix.target.branch }} \
            --repo $GITHUB_REPOSITORY \
            -f target=${{ matrix.target.input_target }} \
            -f log_level=${{ matrix.target.log_level }} \
            -f latest-builder=${{ matrix.target.latest_builder }}          
